### ISSUE TITLE
可以添加几个实用按钮吗？

### ISSUE THREAD

**Issue by weich22** [binjoo/SlimBox2-for-Typecho#2]
缩小倍数，初始大小，放大倍数！还有自定义某个页面图片标题，比如用了文章列表的自定义字段图片图片获取不到图片标题，因为每个文章只输出一个图片，我想获取该文章的主标题！

**Comment by binjoo** [comment]
这只是辅助图片展示效果的，你说的那些功能都不是它的工作。
